//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syracuse.Mobitheque.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syracuse.Mobitheque.UI.AppResource.fr", typeof(AppResource_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} Archimed..
        /// </summary>
        public static string AboutCopyright {
            get {
                return ResourceManager.GetString("AboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact : contact@archimed.fr.
        /// </summary>
        public static string AboutMailContact {
            get {
                return ResourceManager.GetString("AboutMailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous droits réservés.
        /// </summary>
        public static string AboutRigth {
            get {
                return ResourceManager.GetString("AboutRigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site web : https://www.archimed.fr.
        /// </summary>
        public static string AboutWebLink {
            get {
                return ResourceManager.GetString("AboutWebLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon compte.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant.
        /// </summary>
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette page mémorise les comptes précédemment authentifiés et vous permet de vous connecter à ces comptes en un clic. Pour enregistrer un nouveau compte cliquer sur:.
        /// </summary>
        public static string AddAccountTuto {
            get {
                return ResourceManager.GetString("AddAccountTuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réserver.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible.
        /// </summary>
        public static string BookingAvailable {
            get {
                return ResourceManager.GetString("BookingAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente.
        /// </summary>
        public static string BookingWait {
            get {
                return ResourceManager.GetString("BookingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma carte.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se procurer le document.
        /// </summary>
        public static string Copies {
            get {
                return ResourceManager.GetString("Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etats de collection .
        /// </summary>
        public static string CopiesCollectionStatements {
            get {
                return ResourceManager.GetString("CopiesCollectionStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce compte de l&apos;application.
        /// </summary>
        public static string DeleteAppAccount {
            get {
                return ResourceManager.GetString("DeleteAppAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes demandes.
        /// </summary>
        public static string DemandsUser {
            get {
                return ResourceManager.GetString("DemandsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Département.
        /// </summary>
        public static string DepartmentTitle {
            get {
                return ResourceManager.GetString("DepartmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulter en ligne.
        /// </summary>
        public static string DigitalDocumentLink {
            get {
                return ResourceManager.GetString("DigitalDocumentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur: nous ne somme pas parvenis à contacter les informations de votre Bibliothéque.
        /// </summary>
        public static string ErrorLibraryWebSite {
            get {
                return ResourceManager.GetString("ErrorLibraryWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prolonger le document :.
        /// </summary>
        public static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrer.
        /// </summary>
        public static string FilterOption {
            get {
                return ResourceManager.GetString("FilterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url d&apos;établissement.
        /// </summary>
        public static string LibraryTitle {
            get {
                return ResourceManager.GetString("LibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger plus.
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette application necessite une connexion internet veuillez verifier votre reseau.
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne plus afficher.
        /// </summary>
        public static string NeverShowAgain {
            get {
                return ResourceManager.GetString("NeverShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En ce moment.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun résultat ne correspond à votre recherche.
        /// </summary>
        public static string NoSearchResults {
            get {
                return ResourceManager.GetString("NoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas de réservation en cours.
        /// </summary>
        public static string NotCurrentBooking {
            get {
                return ResourceManager.GetString("NotCurrentBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il n a pas de nouveautés pour le moment.
        /// </summary>
        public static string NotCurrentEvent {
            get {
                return ResourceManager.GetString("NotCurrentEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas de prêt en cours.
        /// </summary>
        public static string NotCurrentLoan {
            get {
                return ResourceManager.GetString("NotCurrentLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Voulez-vous déclarer les différents comptes de votre famille ?.
        /// </summary>
        public static string OtherAccountPart2Tuto {
            get {
                return ResourceManager.GetString("OtherAccountPart2Tuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gérer vos comptes ici et basculez rapidement d&apos;un profil à l&apos;autre..
        /// </summary>
        public static string OtherAccountPart3Tuto {
            get {
                return ResourceManager.GetString("OtherAccountPart3Tuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez plusieurs comptes dans différentes bibliothèques ?.
        /// </summary>
        public static string OtherAccountPartTuto {
            get {
                return ResourceManager.GetString("OtherAccountPartTuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérez l&apos;ensemble de vos comptes au même endroit.
        /// </summary>
        public static string OtherAccountTitleTuto {
            get {
                return ResourceManager.GetString("OtherAccountTitleTuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        public static string PasswordForget {
            get {
                return ResourceManager.GetString("PasswordForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trier.
        /// </summary>
        public static string SortOption {
            get {
                return ResourceManager.GetString("SortOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basculer sur ce compte.
        /// </summary>
        public static string SwitchAccount {
            get {
                return ResourceManager.GetString("SwitchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que souhaitez-vous faire?.
        /// </summary>
        public static string SwitchDeleteAccountPopupTitle {
            get {
                return ResourceManager.GetString("SwitchDeleteAccountPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma synthèse.
        /// </summary>
        public static string Synthesis {
            get {
                return ResourceManager.GetString("Synthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
